name: issuesPipeline

on:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned]
  pull_request:
    types: opened
    branches:
      - main
      
jobs:
  information:
    runs-on: ubuntu-latest
    steps:
      - name: Output the event details
        run: echo '${{ toJson(github.event) }}'
