name: issuesPipeline

on:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned]
  pull_request:
    types: [opened, closed]
    branches:
      - main
      - 'dev-*' # to include any branch that starts with "dev-"
      - 'feature/*' # to include any branch that starts with "feature/"
      - 'bugfix/*' # to include any branch that starts with "bugfix/"
    branches_ignore:
      - 'dependabot/*' # to exclude any branch that starts with "dependabot/"
    
jobs:
  information:
    runs-on: ubuntu-latest
    steps:
      - name: Output the event details
        run: echo '${{ toJson(github.event) }}'
