name: Project 2 flow

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  all:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name:  checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
         node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run build script
        run: npm run build

  